In [2]:
import numpy as np 
import pandas as pd

In [4]:
pd.read_csv("../data/raw/ncbi/complete_metadata.csv")

,biosample_id,accession,organism,strain,isolation_source,host,collection_date,geo_loc_name,amr_genotypes,amr_phenotypes,disease,sra_accession,assembly_accession,assembly_status,ftp_path_refseq,ftp_path_genbank,organism_query
0,54875024,SAMN54875024,NaN,PNUSAE221323,stool,NaN,2026-01-07,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Escherichia coli
1,54875022,SAMN54875022,NaN,PNUSAE221322,stool,NaN,2026-01-09,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Escherichia coli
2,54875019,SAMN54875019,NaN,PNUSAE221320,stool,NaN,2025-12-31,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Escherichia coli
3,54874631,SAMN54874631,NaN,PNUSAE221325,stool,NaN,2026-01-04,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Escherichia coli
4,54874628,SAMN54874628,NaN,PNUSAE221321,stool,NaN,2025-12-30,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Escherichia coli
5,54853498,SAMEA120970212,Klebsiella pneumoniae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Klebsiella pneumoniae
6,54832029,SAMEA120970146,Klebsiella pneumoniae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Klebsiella pneumoniae
7,54821146,SAMEA120970149,Klebsiella pneumoniae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Klebsiella pneumoniae
8,54815314,SAMEA120969541,Klebsiella pneumoniae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Klebsiella pneumoniae
9,54872776,SAMN54872776,NaN,NaN,sputum,Homo sapiens,2026,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Klebsiella pneumoniae
10,54875861,SAMN54875861,NaN,NaN,mobile device,NaN,2020-04,Germany: Frankfurt am Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Staphylococcus aureus
11,54875860,SAMN54875860,NaN,NaN,mobile device,NaN,2019-07,Germany: Frankfurt am Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Staphylococcus aureus
12,54875859,SAMN54875859,NaN,NaN,mobile device,NaN,2019-06,Germany: Frankfurt am Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Staphylococcus aureus
13,54875858,SAMN54875858,NaN,NaN,mobile device,NaN,2019-06,Germany: Frankfurt am Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Staphylococcus aureus
14,54875857,SAMN54875857,NaN,NaN,mobile device,NaN,2019-06,Germany: Frankfurt am Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Staphylococcus aureus
15,54872780,SAMN54872780,NaN,NaN,urine,Homo sapiens,2026,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Acinetobacter baumannii
16,54872779,SAMN54872779,NaN,NaN,wound,Homo sapiens,2026,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Acinetobacter baumannii
17,54872778,SAMN54872778,NaN,NaN,sputum,Homo sapiens,2026,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Acinetobacter baumannii
18,54872777,SAMN54872777,NaN,NaN,Tissue,Homo sapiens,2026,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Acinetobacter baumannii
19,54872594,SAMN54872594,NaN,NaN,respiratory,Homo sapiens,2025,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Acinetobacter baumannii

In [6]:
pd.read_csv("../data/raw/patric/genomes_metadata.csv")

,assembly_accession,bioproject_accession,biosample_accession,cell_shape,class,common_name,completion_date,contigs,culture_collection,date_inserted,...,body_sample_site,antimicrobial_resistance,host_age,host_gender,other_environmental,salinity,reference_genome,longitude,latitude,isolation_site
0,GCA_000184185.1,PRJNA48011,SAMN02602978,Bacilli,Gammaproteobacteria,Escherichia_coli_W,2016-07-25T00:00:00Z,1,ATCC:9637,2017-12-29T21:45:17.926Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GCA_000184185.1,PRJNA48011,SAMN02602978,Bacilli,Gammaproteobacteria,Escherichia_coli_W,2016-07-25T00:00:00Z,1,ATCC:9637,2017-12-29T21:45:18.042Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,Escherichia_coli_phage_EH297,2003-03-03T00:00:00Z,1,NaN,2025-12-07T19:02:09.291Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GCA_000027125.1,PRJEA40647,SAMEA2272277,Bacilli,Gammaproteobacteria,Escherichia_coli_042,2016-07-25T00:00:00Z,1,NaN,2017-12-30T06:13:22.076Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GCA_000529855.1,PRJEB4814,SAMEA3138867,NaN,Gammaproteobacteria,Escherichia_coli_ISC7,NaN,196,NaN,2014-12-08T22:11:27.515Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,GCA_020254765.1,PRJNA766794,SAMN21876336,NaN,Gammaproteobacteria,Acinetobacter_baumannii,2021-10-04T00:00:00Z,74,NaN,2021-11-30T13:35:56.069Z,...,NaN,['Susceptible'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,GCA_020254845.1,PRJNA766794,SAMN21876331,NaN,Gammaproteobacteria,Acinetobacter_baumannii,2021-10-04T00:00:00Z,158,NaN,2021-11-30T13:36:26.205Z,...,NaN,['Susceptible'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,GCA_020254905.1,PRJNA766794,SAMN21876374,NaN,Gammaproteobacteria,Acinetobacter_baumannii,2021-10-04T00:00:00Z,157,NaN,2021-11-30T13:34:30.623Z,...,NaN,['Susceptible'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,GCA_020254945.1,PRJNA766794,SAMN21876363,NaN,Gammaproteobacteria,Acinetobacter_baumannii,2021-10-04T00:00:00Z,83,NaN,2021-11-30T13:34:37.413Z,...,NaN,['Susceptible'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,GCA_020255105.1,PRJNA766794,SAMN21876378,NaN,Gammaproteobacteria,Acinetobacter_baumannii,2021-10-04T00:00:00Z,102,NaN,2021-11-30T13:35:03.903Z,...,NaN,['Susceptible'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN